import t_shirt from '../../../assets/img/White T-shirts.webp'; // Asegúrate de que las rutas sean correctas
import t_shirt_red from '../../../assets/img/Red-T-shirts.jpg';
import hoodie from '../../../assets/img/Gray-hoodie.jpg';
import jeans from '../../../assets/img/Classic-Blue-Jeans.jpg';
import dress from '../../../assets/img/Summer-Floral-Dress.jpg';
import cap from '../../../assets/img/baseball-cap-black.jpg';
import jacket from '../../../assets/img/t-shirt.jpg';
import shorts from '../../../assets/img/t-shirt.jpg';
import sneakers from '../../../assets/img/t-shirt.jpg';
import sandals from '../../../assets/img/t-shirt.jpg';
import socks from '../../../assets/img/t-shirt.jpg';
import belt from '../../../assets/img/t-shirt.jpg';
import scarf from '../../../assets/img/t-shirt.jpg';
import sunglasses from '../../../assets/img/t-shirt.jpg';
import backpack from '../../../assets/img/t-shirt.jpg';
import wallet from '../../../assets/img/t-shirt.jpg';
import beanie from '../../../assets/img/t-shirt.jpg';
import tank_top from '../../../assets/img/t-shirt.jpg';
import blouse from '../../../assets/img/t-shirt.jpg';
import cardigan from '../../../assets/img/t-shirt.jpg';
import pajama from '../../../assets/img/t-shirt.jpg';
import suit from '../../../assets/img/t-shirt.jpg';
import skirt from '../../../assets/img/t-shirt.jpg';
import overalls from '../../../assets/img/t-shirt.jpg';
import polo_shirt from '../../../assets/img/t-shirt.jpg';
import windbreaker from '../../../assets/img/t-shirt.jpg';
import dress_shirt from '../../../assets/img/t-shirt.jpg';
import fleece_jacket from '../../../assets/img/t-shirt.jpg';
import dress_pants from '../../../assets/img/t-shirt.jpg';
import ankle_boots from '../../../assets/img/t-shirt.jpg';
import loafers from '../../../assets/img/t-shirt.jpg';

const ArrayProductsGallery = [
    {
        img: t_shirt,
        alltr: 'T-shirt White',
        star: '★★★★★',
        name_product: 'White T-shirt',
        price: '$19.99',
        description: 'Una cómoda y elegante camiseta blanca, perfecta para cualquier ocasión.',
        fabric: '100% Algodón',
        colors: ['#FFFFFF', '#000000', '#FF5733'],
    },
    {
        img: t_shirt_red,
        alltr: 'T-shirt Red',
        star: '★★★★☆',
        name_product: 'Red T-shirt',
        price: '$21.99',
        description: 'Camiseta roja vibrante que destaca en cualquier lugar.',
        fabric: '100% Poliéster',
        colors: ['#FF5733', '#C70039', '#900C3F'],
    },
    {
        img: hoodie,
        alltr: 'Hoodie Gray',
        star: '★★★★★',
        name_product: 'Gray Hoodie',
        price: '$39.99',
        description: 'Un hoodie gris suave y acogedor para días fríos.',
        fabric: '80% Algodón, 20% Poliéster',
        colors: ['#A9A9A9', '#696969', '#D3D3D3'],
    },
    {
        img: jeans,
        alltr: 'Blue Jeans',
        star: '★★★★☆',
        name_product: 'Classic Blue Jeans',
        price: '$49.99',
        description: 'Jeans clásicos de corte recto, perfectos para cualquier ocasión.',
        fabric: '100% Denim',
        colors: ['#0000FF', '#1E90FF'],
    },
    {
        img: dress,
        alltr: 'Summer Dress',
        star: '★★★★★',
        name_product: 'Summer Floral Dress',
        price: '$34.99',
        description: 'Un vestido floral ligero, ideal para el verano.',
        fabric: '100% Poliéster',
        colors: ['#FF69B4', '#FFD700'],
    },
    {
        img: cap,
        alltr: 'Baseball Cap',
        star: '★★★★☆',
        name_product: 'Baseball Cap Black',
        price: '$15.99',
        description: 'Una gorra de béisbol negra clásica.',
        fabric: '100% Algodón',
        colors: ['#000000', '#FFFFFF'],
    },
    {
        img: jacket,
        alltr: 'Leather Jacket',
        star: '★★★★★',
        name_product: 'Black Leather Jacket',
        price: '$129.99',
        description: 'Chaqueta de cuero negra de alta calidad.',
        fabric: '100% Cuero',
        colors: ['#000000'],
    },
    {
        img: shorts,
        alltr: 'Denim Shorts',
        star: '★★★★☆',
        name_product: 'Denim Shorts',
        price: '$29.99',
        description: 'Shorts de mezclilla cómodos para el verano.',
        fabric: '100% Denim',
        colors: ['#0000FF', '#FFA07A'],
    },
    {
        img: sneakers,
        alltr: 'Sport Sneakers',
        star: '★★★★☆',
        name_product: 'White Sport Sneakers',
        price: '$69.99',
        description: 'Zapatillas deportivas blancas, ideales para el día a día.',
        fabric: 'Malla y Caucho',
        colors: ['#FFFFFF', '#000000'],
    },
    {
        img: sandals,
        alltr: 'Beach Sandals',
        star: '★★★★☆',
        name_product: 'Comfortable Sandals',
        price: '$24.99',
        description: 'Sandalias cómodas y ligeras, perfectas para la playa.',
        fabric: '100% Plástico',
        colors: ['#FFD700', '#FF4500'],
    },
    {
        img: socks,
        alltr: 'Cotton Socks',
        star: '★★★★★',
        name_product: 'Cotton Socks Pack',
        price: '$9.99',
        description: 'Paquete de calcetines de algodón, suaves y cómodos.',
        fabric: '100% Algodón',
        colors: ['#FFFFFF', '#C0C0C0'],
    },
    {
        img: belt,
        alltr: 'Leather Belt',
        star: '★★★★☆',
        name_product: 'Classic Leather Belt',
        price: '$19.99',
        description: 'Cinturón de cuero clásico, ideal para cualquier ocasión.',
        fabric: '100% Cuero',
        colors: ['#000000', '#A52A2A'],
    },
    {
        img: scarf,
        alltr: 'Wool Scarf',
        star: '★★★★★',
        name_product: 'Warm Wool Scarf',
        price: '$15.99',
        description: 'Bufanda de lana suave y cálida.',
        fabric: '100% Lana',
        colors: ['#FF6347', '#6A5ACD'],
    },
    {
        img: sunglasses,
        alltr: 'Sunglasses',
        star: '★★★★☆',
        name_product: 'Stylish Sunglasses',
        price: '$29.99',
        description: 'Gafas de sol elegantes para el verano.',
        fabric: 'Policarbonato',
        colors: ['#000000', '#FFD700'],
    },
    {
        img: backpack,
        alltr: 'Travel Backpack',
        star: '★★★★★',
        name_product: 'Durable Travel Backpack',
        price: '$49.99',
        description: 'Mochila resistente y espaciosa para viajes.',
        fabric: 'Poliéster',
        colors: ['#8B4513', '#A0522D'],
    },
    {
        img: wallet,
        alltr: 'Leather Wallet',
        star: '★★★★☆',
        name_product: 'Classic Leather Wallet',
        price: '$29.99',
        description: 'Billetera de cuero clásica y elegante.',
        fabric: '100% Cuero',
        colors: ['#000000', '#8B4513'],
    },
    {
        img: beanie,
        alltr: 'Wool Beanie',
        star: '★★★★★',
        name_product: 'Warm Wool Beanie',
        price: '$19.99',
        description: 'Gorro de lana suave y cálido.',
        fabric: '100% Lana',
        colors: ['#FF6347', '#4682B4'],
    },
    {
        img: tank_top,
        alltr: 'Tank Top',
        star: '★★★★☆',
        name_product: 'Casual Tank Top',
        price: '$17.99',
        description: 'Top sin mangas ligero y cómodo para el verano.',
        fabric: '100% Algodón',
        colors: ['#FFFFFF', '#FF4500'],
    },
    {
        img: blouse,
        alltr: 'Silk Blouse',
        star: '★★★★★',
        name_product: 'Elegant Silk Blouse',
        price: '$39.99',
        description: 'Blusa de seda elegante, perfecta para ocasiones especiales.',
        fabric: '100% Seda',
        colors: ['#FFC0CB', '#4682B4'],
    },
    {
        img: cardigan,
        alltr: 'Knitted Cardigan',
        star: '★★★★☆',
        name_product: 'Cozy Knitted Cardigan',
        price: '$49.99',
        description: 'Cárdigan de lana acogedor para el invierno.',
        fabric: '100% Lana',
        colors: ['#A9A9A9', '#FFD700'],
    },
    {
        img: pajama,
        alltr: 'Cotton Pajama',
        star: '★★★★★',
        name_product: 'Soft Cotton Pajama',
        price: '$34.99',
        description: 'Pijama de algodón suave, ideal para dormir.',
        fabric: '100% Algodón',
        colors: ['#FFFFFF', '#D3D3D3'],
    },
    {
        img: suit,
        alltr: 'Formal Suit',
        star: '★★★★★',
        name_product: 'Elegant Formal Suit',
        price: '$199.99',
        description: 'Traje formal elegante, perfecto para eventos.',
        fabric: '100% Poliéster',
        colors: ['#000000', '#2F4F4F'],
    },
    {
        img: skirt,
        alltr: 'A-Line Skirt',
        star: '★★★★☆',
        name_product: 'Floral A-Line Skirt',
        price: '$29.99',
        description: 'Falda en línea A con estampado floral.',
        fabric: '100% Poliéster',
        colors: ['#FF69B4', '#FFFACD'],
    },
    {
        img: overalls,
        alltr: 'Denim Overalls',
        star: '★★★★☆',
        name_product: 'Classic Denim Overalls',
        price: '$59.99',
        description: 'Overoles de mezclilla clásicos, cómodos y elegantes.',
        fabric: '100% Denim',
        colors: ['#0000FF', '#A9A9A9'],
    },
    {
        img: polo_shirt,
        alltr: 'Polo Shirt',
        star: '★★★★★',
        name_product: 'Cotton Polo Shirt',
        price: '$24.99',
        description: 'Camisa polo de algodón, ideal para ocasiones informales.',
        fabric: '100% Algodón',
        colors: ['#32CD32', '#FFD700'],
    },
    {
        img: windbreaker,
        alltr: 'Windbreaker Jacket',
        star: '★★★★☆',
        name_product: 'Lightweight Windbreaker',
        price: '$49.99',
        description: 'Chaqueta cortaviento ligera y transpirable.',
        fabric: '100% Poliéster',
        colors: ['#B0C4DE', '#778899'],
    },
    {
        img: dress_shirt,
        alltr: 'Dress Shirt',
        star: '★★★★★',
        name_product: 'Formal Dress Shirt',
        price: '$39.99',
        description: 'Camisa formal ideal para el trabajo y ocasiones especiales.',
        fabric: '100% Algodón',
        colors: ['#FFFFFF', '#4682B4'],
    },
    {
        img: fleece_jacket,
        alltr: 'Fleece Jacket',
        star: '★★★★☆',
        name_product: 'Cozy Fleece Jacket',
        price: '$59.99',
        description: 'Chaqueta de forro polar cómoda y abrigada.',
        fabric: '100% Poliéster',
        colors: ['#A9A9A9', '#2F4F4F'],
    },
    {
        img: dress_pants,
        alltr: 'Dress Pants',
        star: '★★★★☆',
        name_product: 'Elegant Dress Pants',
        price: '$69.99',
        description: 'Pantalones elegantes para combinar con cualquier atuendo.',
        fabric: '100% Poliéster',
        colors: ['#000000', '#A9A9A9'],
    },
    {
        img: ankle_boots,
        alltr: 'Ankle Boots',
        star: '★★★★★',
        name_product: 'Stylish Ankle Boots',
        price: '$79.99',
        description: 'Botas de tobillo elegantes y cómodas.',
        fabric: '100% Cuero',
        colors: ['#000000', '#A52A2A'],
    },
    {
        img: loafers,
        alltr: 'Leather Loafers',
        star: '★★★★☆',
        name_product: 'Classic Leather Loafers',
        price: '$69.99',
        description: 'Mocasines de cuero clásicos y elegantes.',
        fabric: '100% Cuero',
        colors: ['#000000', '#A52A2A'],
    },
];

export default ArrayProductsGallery;
